### ISSUE TITLE
Linux based application needed

### ISSUE THREAD

**Issue by moni-roy** [dipu-bd/UVA-Arena#17]
It is a opensource application. so, please make the application for linux-based platform. Linux is also a open source project, so, if you do this it is helpful for linux user.

**Comment by dipu-bd** [comment]
To make it linux based I need to rebuild the whole application. I am not so familiar with linux application development. Currently I am learning about it. I think it will take me some time to make the run on linux. If anybody wanted to help, it would be great.

**Comment by jgcoded** [comment]
@dipu-bd Have you finalized the way you want do things on linux, or do contributors have free reign to the implementation?
