### ISSUE TITLE
Submit a problem

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/UVA-Arena#22]
Many is having trouble with problem submission. Submit page opens but just UVA Home page showing. It is a problem with Internet explorer cookies. need to fix it soon.

**Comment by DebasishOpu** [comment]
I am trying to enter my username "debasishopu". But it always shows [Error: debasishopu doesn't exist]! Help me please.

**Comment by dipu-bd** [comment]
Try to search you username in uHunt. It really doesn't exist.

**Comment by dipu-bd** [comment]
the problem is partially solved.
