### ISSUE TITLE
udebug not working on windows 10

### ISSUE THREAD

**Issue by ghost** [dipu-bd/UVA-Arena#31]
I have moved from windows 7 to windows 10. udebug is not working now. Any reasons for that?

**Comment by dipu-bd** [comment]
It is a problem with IE browser. I am building UVA Arena 2 to solve all the issues. It will take some time to release it.

**Comment by gaddevarunteja** [comment]
Can you please mention the approximate date? I want it to be released as
soon as possible.

**Comment by dipu-bd** [comment]
Me too, want to release it as soon as possible. But I have been very busy lately and can not work on it as much as I should. I hope to release it after my summer vacation, possibly around June-July.

**Comment by TheShikharGupta** [comment]
Hello, I too am facing the same issue as ghost, unable to view inputs on uDebug. Hopefully the new version will be out soon.
P.S.: Find the software very useful, keep it up :)
